vaadin/vaadin-app-layout

- .travis.yml
- bower.json
- src/vaadin-app-layout.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-app-layout/9)
> Add License checker

- bower.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-app-layout/11)
> Update vaadin-demo-helpers version

- .gitignore
- .travis.yml
- README.md
- analysis.json
- bower.json
- demo/demo-shell.html
- demo/demos.json
- demo/iframe.html
- demo/index.html
- gulpfile.js
- package.json
- src/vaadin-app-layout.html
- vaadin-directory-description.md
- wct.conf.js
Fixes #15 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-app-layout/16)
> Make component P3 compatible

- .travis.yml
- bower.json
- src/vaadin-app-layout.html
- wct.conf.js
Update other dependencies to stable, sync tests and build with skeleton
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-app-layout/18)
> Update license checker version

- LICENSE
- bower.json
- package.json
- src/vaadin-app-layout.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-app-layout/23)
> Change license from Apache to CVALv3

- analysis.json
- demo/element-basic-demos.html
- demo/index.html
- src/vaadin-app-layout.html
Add max-width styles for navbar elements
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-app-layout/24)
> Add more demos

- analysis.json
- demo/element-basic-demos.html
- package.json
- src/vaadin-app-layout.html
Set fixed height to branding and navbar, since branding has position absolute
Prepare for alpha1 release
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-app-layout/26)
> Fix how branding is displayed in IE11

- README.md
- src/vaadin-app-layout.html
- vaadin-directory-description.md
Make screenshots bigger
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-app-layout/27)
> Add suitable roles to the elements

- analysis.json
- src/vaadin-app-layout.html
Fixes #32
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-app-layout/36)
> Improve documentation

- src/vaadin-app-layout.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-app-layout/41)
> Add aria-live to improve feedback on content change

- package.json
- src/vaadin-app-layout.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-app-layout/43)
> 1.0.0-alpha2

- src/vaadin-app-layout.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-app-layout/44)
> Fix menu position for IE11

- bower.json
- package.json
- src/vaadin-app-layout.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-app-layout/45)
> Prepare for beta

- LICENSE
- README.md
- bower.json
- package.json
- src/vaadin-app-layout.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-app-layout/47)
> Change license to Apache 2.0

- .travis.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-app-layout/50)
> Pin FF version while wct issue is checked

- wct.conf.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-app-layout/52)
> Test iOS 10 on ipad

- package.json
- src/vaadin-app-layout.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-app-layout/53)
> Version 1.0.0

- test/vaadin-app-layout-test.html
- wct.conf.js
Add retry rule
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-app-layout/54)
> Ignore flaky test on iOS 10.3

- src/vaadin-app-layout-mixin.html
- test/.eslintrc.json
- test/vaadin-app-layout-test.html
- wct.conf.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-app-layout/73)
> Add some tests and increase coverage

- src/vaadin-app-layout.html
Closes https://github.com/vaadin/vaadin-app-layout/issues/64
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-app-layout/75)
> Remove orientation

- src/vaadin-app-layout.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-app-layout/81)
> Fix typo in documentation

- src/vaadin-app-layout.html
Notify is necessary to allow synchronization with Flow.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-app-layout/83)
> Added notify to properties

- src/vaadin-app-layout.html
- src/vaadin-drawer-toggle.html
- App Layout documentation
- Drawer Toggle documentation
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-app-layout/85)
> Add component level documentation

- src/vaadin-app-layout.html
- src/vaadin-drawer-toggle.html
- Add focus to drawer when it gets opened
- Add aria-label to vaadin-toggle-drawer
Fixes #65
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-app-layout/84)
> Add some ARIA rules to drawer in overlay mode

- demo/element-basic-demos.html
- demo/index.html
- src/vaadin-app-layout.html
- test/vaadin-app-layout-test.html
- `primarySection` accepts two values: `navbar` and `drawer`
- add tests and demo
- make demo look a bit better by increasing its height
- change documentation
Fixes #87
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-app-layout/90)
> Rename drawerFirst to primarySection

- bower.json
- magi-p3-post.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-app-layout/95)
> Update vaadin-tabs dep to 3.0.0 final

- wct.conf.js
- Align it with element skeleton
- Sauce labs dropped Safari 9
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-app-layout/96)
> Update browser versions

- demo/element-basic-demos.html
- src/vaadin-app-layout.html
Fixes #97
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-app-layout/99)
> Improve touch-optimized demo and docs

- demo/index-lumo.html
- demo/index-material.html
- demo/index.html
- src/vaadin-app-layout.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-app-layout/103)
> Include viewport-fit=cover in docs and demos

- src/vaadin-app-layout.html
Add instruction of how to activate "content scrolling"
Fixes #77
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-app-layout/105)
> Add documentation about scrolling areas

- demo/element-basic-demos.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-app-layout/115)
> close drawer after navigation in demo with router

- index.html
- package.json
- src/vaadin-app-layout-mixin.ts
- src/vaadin-app-layout.ts
- vaadin-app-layout.html
- vaadin-app-layout.ts
- vaadin-drawer-toggle.html
- vaadin-drawer-toggle.ts
> LitElement conversion part 4: API docs

- package.json
> [3.0.0-alpha1] Dependency Typo Fix

- src/vaadin-app-layout-mixin.ts
- test/unit/app-layout.test.ts
Same as #146 but for `next` branch. 
Code and tests are slightly different but the overall idea is the same.
> fix: update touch optimized on slot change
